permissions:
  contents: write
  pull-requests: write

name: Publish Stable Release

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  publish_stable:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-stable.yml@e1770fb608f8c39ab886ff336f6470ee17747b0d # dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
    with:
      version_file: 'hivemind_core/version.py'
      publish_pypi: true
      notify_matrix: true
